name: CI

on:
  push:
    branches:
      - master

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v3
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-backend-${{ hashFiles('backend/package-lock.json') }}
      - name: Install dependencies
        run: cd backend && npm install
      - name: Build
        run: cd backend && npm run build
      - name: Lint
        run: cd backend && npm run lint
      - name: Type check
        run: cd backend && npm run typecheck
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v3
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: web/node_modules
          key: ${{ runner.os }}-web-${{ hashFiles('web/package-lock.json') }}
      - name: Install dependencies
        run: cd web && npm install
      - name: Build
        run: cd web && npm run build
      - name: Lint
        run: cd web && npm run lint
      - name: Type check
        run: cd web && npm run typecheck
