name: Migrate database

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v3
      - name: Change directory to backend
        run: cd backend
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Prisma migration
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
