name: Migrate database

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: cd backend && npm install
      - name: Build
        run: cd backend && npm run build
      - name: Prisma migration
        run: cd backend && npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
